intents:
  - greet
  - thankyou
  - goodbye
  - fund_search
  - fund_search_with_type
  - fund_search_with_achievement
  - fund_search_with_company
  - fund_search_with_topic
  - inform

slots: #keep track of context and handle multi-turn dialogue
  fund_type:
    type: list 
  fund_company:
    type: list
  fund_achievement_duration:
    type: text # (unset)->0 (set)->1
  fund_achievement_topk:
    type: text
  fund_topic:
    type: list # (len==0)->0 (len>0)->1
  #institutional_rating_institution:
  # type: text
  #institutional_rating_rate:
  # type: text
  fund_sacle:
    type: categorical # one-hot encoding
    values:
    - "小于2亿元"
    - "小于10亿元"
    - "小于50亿元"
    - "小于100亿元"
    - "大于100亿元"
  #found_years:
  #  type: text
  matches:
    type: unfeaturized # never influences the prediction
  requested_slot:
    type: unfeaturized

entities: # different slot may share same entity
- fund_type
- fund_company
- duration
- topk
- fund_topic
#- institutional_rating
#- fund_sacle
#- found_years

actions: # utter+templates,custom actions
- utter_greet
- utter_ask_type
- utter_ask_company
- utter_ask_fund_achievement_duration
- utter_ask_fund_achievement_topk
- utter_ask_topic
#- utter_ask_rating
#- utter_ask_sacle
#- utter_ask_years
- utter_working_on_it
- bot.actions.ActionFundSearchResponse
- bot.actions.ActionFundSearchWithAchievement
- utter_response_fund
- utter_goodbye

templates:
  utter_greet:
  - text: "你好，请说出你对基金的偏好"

  utter_working_on_it:
  - text: "正在查询中，请稍后 ..."

  utter_goodbye:
  - text: "拜拜！"
  - text: "goodbye :("  # Variations:random pick one

  utter_ask_type:
  - text: "你关注什么类型的基金呢？"
    buttons:
    - title: "股票型"
      payload: "股票型"
    - title: "混合型"
      payload: "混合型"
    - title: "债卷型"
      payload: "债卷型"
    - title: "指数型"
      payload: "指数型"
    - title: "QDII"
      payload: "QDII"
    - title: "FOF"
      payload: "FOF"

  utter_ask_company:
  - text: "你关注哪家公司的基金呢？"
    buttons:
    - title: "华夏"
      payload: "华夏"
    - title: "嘉实"
      payload: "嘉实"
    - title: "易方达"
      payload: "易方达"
    - title: "南方"
      payload: "南方"
    - title: "中银"
      payload: "中银"
    - title: "广发"
      payload: "广发"
    - title: "工银"
      payload: "工银"
    - title: "博时"
      payload: "博时"
    - title: "华安"
      payload: "华安"

  #utter_ask_achievement:
  #- text: "你对基金的表现有什么要求？"

  utter_ask_fund_achievement_duration:
  - text: "你关注基金多久的表现呢？"

  utter_ask_fund_achievement_topk:
  - text: "你关注表现排名前多少的基金呢？"

  utter_ask_topic:
  - text: "你关注什么话题的基金呢？"

  #utter_ask_rating:
  #- text: "你对基金的评级有什么要求？"

  #utter_ask_sacle:
  #- text: "你对基金的规模有什么要求？"

  #utter_ask_years:
  #- text: "你对基金的成立年限有什么要求？"

  utter_response_fund:
  - text: "{matches}" # Variables:variable filled by slot

  utter_other:
  - text: "我暂时听不懂这句话。"
